title: Idiot's Domain

author:
  name: >
  email: bbt1 [at] hw [dot] ac [dot] uk

description: >
  This is my blog. There are many like it, but this one is mine.

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

social_links:
  twitter: ben_trevett
  github:  bentrevett

header_pages:
 - about.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
