title: Big Idiot's Big Idiot Blog

author:
  name: Ben Trevett
  email: bbt1@hw.ac.uk

description: >
  This is my blog. There are many like it, but this one is mine.

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: ben_trevett
    github:  bentrevett

header_pages:
 - about.md
 - wiki

google_analytics: UA-124821553-1

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
